[build]
  base = "felipecordero.github.io"
  publish = "public"
  command = "npm install && npm run build:css && hugo --gc --minify -b $URL"

[build.environment]
  HUGO_VERSION = "0.155.3"
  NODE_VERSION = "22"
  TZ = "Europe/Oslo"
  GIT_SUBMODULE_STRATEGY = "recursive"
